### ISSUE TITLE
Chains of multiple actions

### ISSUE THREAD

**Issue by Sennahoi** [muesli/beehive#194]
I would like to create a chain of multiple actions, e.g.

1. receive data from a webhook (webserver)
2. Put this data into a script that extracts some parts
3. Forward extracted parts to the a web client bee to send it to some endpoint

As far as it seems to me, a chain can only consist of 2 parts: An event bee and an action bee. 
Can I put other beens in between? Or is there another way I'm not aware of?

Thanks
Johannes

**Comment by Larpon** [comment]
Also useful when wanting to notify of some action is done

1. `Cron` Every 2 minutes
2. `Execute command` `/do/hard/work`
3. `Desktop notification` - `Job resulted in {{.stdout}}`

**Comment by LorenzoAncora** [comment]
A chain with only two rings is of little use.

**Comment by Larpon** [comment]
Cool, thanks for your input - but how do we do this from the UI or config? I'm not sure how you *link* hives?

**Comment by LorenzoAncora** [comment]
> Cool, thanks for your input - but how do we do this from the UI or config? I'm not sure how you link hives?

@Larpon it is neither easy nor intuitive but it can be done: the only way to link the hives is to exploit the fact that you can have multiple bees with the same hive but with a different name.

### Example

You have 3 bees: "Cron" hive as A1, "HTTP client" hive as B1 and "Exec" hive as A2.
You can create 2 chains:

1. "A1" event -> "**B1**" action;
2. "**B1**" event -> "A2" action.

It works like dominoes, because the end of the first chain will trigger the second.
Assuming that "A1" is triggered every hour: at the end of the first hour it will start B1 which will make an HTTP GET request; when (and if) the HTTP GET request is complete it will trigger the "get" event that will start the second chain, which will trigger A2's action.

I hope I was clear. :-)

**Comment by LorenzoAncora** [comment]
@Sennahoi if the problem is solved you should close the Issue.
@Larpon all right? other difficulties?

**Comment by Sennahoi** [comment]
Thanks for your help.

**Comment by LorenzoAncora** [comment]
> Thanks for your help.

@Sennahoi  You are welcome.
